# Asteroid using Logistic Regression and Random Forest

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('Asteroid.csv')
df

C:\Users\MYPC~1\AppData\Local\Temp/ipykernel_5524/1105021079.py:1: DtypeWarning: Columns (3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('Asteroid.csv')

,id,spkid,full_name,pdes,name,prefix,neo,pha,H,diameter,...,sigma_i,sigma_om,sigma_w,sigma_ma,sigma_ad,sigma_n,sigma_tp,sigma_per,class,rms
0,a0000001,2000001,1 Ceres,1,Ceres,NaN,N,N,3.400,939.400,...,4.608900e-09,6.168800e-08,6.624800e-08,7.820700e-09,1.111300e-11,1.196500e-12,3.782900e-08,9.415900e-09,MBA,0.43301
1,a0000002,2000002,2 Pallas,2,Pallas,NaN,N,N,4.200,545.000,...,3.469400e-06,6.272400e-06,9.128200e-06,8.859100e-06,4.961300e-09,4.653600e-10,4.078700e-05,3.680700e-06,MBA,0.35936
2,a0000003,2000003,3 Juno,3,Juno,NaN,N,N,5.330,246.596,...,3.223100e-06,1.664600e-05,1.772100e-05,8.110400e-06,4.363900e-09,4.413400e-10,3.528800e-05,3.107200e-06,MBA,0.33848
3,a0000004,2000004,4 Vesta,4,Vesta,NaN,N,N,3.000,525.400,...,2.170600e-07,3.880800e-07,1.789300e-07,1.206800e-06,1.648600e-09,2.612500e-10,4.103700e-06,1.274900e-06,MBA,0.39980
4,a0000005,2000005,5 Astraea,5,Astraea,NaN,N,N,6.900,106.699,...,2.740800e-06,2.894900e-05,2.984200e-05,8.303800e-06,4.729000e-09,5.522700e-10,3.474300e-05,3.490500e-06,MBA,0.52191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958519,bPLS6013,3246801,(6013 P-L),6013 P-L,NaN,NaN,N,N,17.135,NaN,...,6.969000e+00,7.433000e+00,4.631100e+01,2.738300e+01,1.041200e+00,1.652100e-01,1.309700e+02,7.264900e+02,MBA,0.23839
958520,bPLS6331,3246834,(6331 P-L),6331 P-L,NaN,NaN,N,N,18.500,NaN,...,1.563500e-05,5.598600e-05,2.380400e-04,1.298200e-04,2.418900e-08,3.346100e-09,4.690200e-04,1.578500e-05,MBA,0.53633
958521,bPLS6344,3013075,(6344 P-L),6344 P-L,NaN,NaN,Y,Y,20.400,NaN,...,1.853300e-05,5.691700e-05,8.969200e-05,5.272600e-05,1.650100e-07,1.101600e-08,2.830600e-04,9.127500e-05,APO,0.51556
958522,bT2S2060,3246457,(2060 T-2),2060 T-2,NaN,NaN,N,N,18.071,NaN,...,5.448800e-01,4.391600e+00,1.898800e+01,1.083800e+01,7.171600e-01,1.016700e-01,3.898400e+01,5.035500e+02,MBA,0.25641
958523,bT3S2678,3246553,(2678 T-3),2678 T-3,NaN,NaN,N,N,18.060,NaN,...,1.102300e+00,3.117000e-01,1.284300e+00,4.736100e-01,1.626700e-01,2.487900e-02,5.523600e+00,1.064800e+02,MBA,0.26980

In [3]:
df.shape

(958524, 45)

In [4]:
#To make all columns visible
pd.set_option('display.max_columns',None)

In [5]:
df.head()

,id,spkid,full_name,pdes,name,prefix,neo,pha,H,diameter,albedo,diameter_sigma,orbit_id,epoch,epoch_mjd,epoch_cal,equinox,e,a,q,i,om,w,ma,ad,n,tp,tp_cal,per,per_y,moid,moid_ld,sigma_e,sigma_a,sigma_q,sigma_i,sigma_om,sigma_w,sigma_ma,sigma_ad,sigma_n,sigma_tp,sigma_per,class,rms
0,a0000001,2000001,1 Ceres,1,Ceres,NaN,N,N,3.40,939.400,0.0900,0.200,JPL 47,2458600.5,58600,20190427.0,J2000,0.076009,2.769165,2.558684,10.594067,80.305531,73.597695,77.372098,2.979647,0.213885,2.458239e+06,2.018043e+07,1683.145703,4.608202,1.59478,620.640533,4.819000e-12,1.032800e-11,1.956900e-11,4.608900e-09,6.168800e-08,6.624800e-08,7.820700e-09,1.111300e-11,1.196500e-12,3.782900e-08,9.415900e-09,MBA,0.43301
1,a0000002,2000002,2 Pallas,2,Pallas,NaN,N,N,4.20,545.000,0.1010,18.000,JPL 37,2459000.5,59000,20200531.0,J2000,0.229972,2.773841,2.135935,34.832932,173.024741,310.202392,144.975675,3.411748,0.213345,2.458321e+06,2.018072e+07,1687.410992,4.619880,1.23429,480.348639,3.193400e-08,4.033700e-09,8.832200e-08,3.469400e-06,6.272400e-06,9.128200e-06,8.859100e-06,4.961300e-09,4.653600e-10,4.078700e-05,3.680700e-06,MBA,0.35936
2,a0000003,2000003,3 Juno,3,Juno,NaN,N,N,5.33,246.596,0.2140,10.594,JPL 112,2459000.5,59000,20200531.0,J2000,0.256936,2.668285,1.982706,12.991043,169.851482,248.066193,125.435355,3.353865,0.226129,2.458446e+06,2.018112e+07,1592.013769,4.358696,1.03429,402.514639,3.052000e-08,3.471800e-09,8.139200e-08,3.223100e-06,1.664600e-05,1.772100e-05,8.110400e-06,4.363900e-09,4.413400e-10,3.528800e-05,3.107200e-06,MBA,0.33848
3,a0000004,2000004,4 Vesta,4,Vesta,NaN,N,N,3.00,525.400,0.4228,0.200,JPL 35,2458600.5,58600,20190427.0,J2000,0.088721,2.361418,2.151909,7.141771,103.810804,150.728541,95.861938,2.570926,0.271609,2.458248e+06,2.018051e+07,1325.432763,3.628837,1.13948,443.451432,2.332100e-10,1.514300e-09,1.928600e-09,2.170600e-07,3.880800e-07,1.789300e-07,1.206800e-06,1.648600e-09,2.612500e-10,4.103700e-06,1.274900e-06,MBA,0.39980
4,a0000005,2000005,5 Astraea,5,Astraea,NaN,N,N,6.90,106.699,0.2740,3.140,JPL 114,2459000.5,59000,20200531.0,J2000,0.190913,2.574037,2.082619,5.367427,141.571026,358.648418,17.846343,3.065455,0.238661,2.458926e+06,2.020032e+07,1508.414421,4.129814,1.09575,426.433027,2.373700e-08,3.970900e-09,6.092400e-08,2.740800e-06,2.894900e-05,2.984200e-05,8.303800e-06,4.729000e-09,5.522700e-10,3.474300e-05,3.490500e-06,MBA,0.52191

In [6]:
df.columns

Index(['id', 'spkid', 'full_name', 'pdes', 'name', 'prefix', 'neo', 'pha', 'H',
       'diameter', 'albedo', 'diameter_sigma', 'orbit_id', 'epoch',
       'epoch_mjd', 'epoch_cal', 'equinox', 'e', 'a', 'q', 'i', 'om', 'w',
       'ma', 'ad', 'n', 'tp', 'tp_cal', 'per', 'per_y', 'moid', 'moid_ld',
       'sigma_e', 'sigma_a', 'sigma_q', 'sigma_i', 'sigma_om', 'sigma_w',
       'sigma_ma', 'sigma_ad', 'sigma_n', 'sigma_tp', 'sigma_per', 'class',
       'rms'],
      dtype='object')

In [7]:
df.dtypes

id                 object
spkid               int64
full_name          object
pdes               object
name               object
prefix             object
neo                object
pha                object
H                 float64
diameter          float64
albedo            float64
diameter_sigma    float64
orbit_id           object
epoch             float64
epoch_mjd           int64
epoch_cal         float64
equinox            object
e                 float64
a                 float64
q                 float64
i                 float64
om                float64
w                 float64
ma                float64
ad                float64
n                 float64
tp                float64
tp_cal            float64
per               float64
per_y             float64
moid              float64
moid_ld           float64
sigma_e           float64
sigma_a           float64
sigma_q           float64
sigma_i           float64
sigma_om          float64
sigma_w           float64
sigma_ma          float64
sigma_ad          float64
sigma_n           float64
sigma_tp          float64
sigma_per         float64
class              object
rms               float64
dtype: object

In [8]:
(df.isnull().sum()/df.shape[0])*100

id                 0.000000
spkid              0.000000
full_name          0.000000
pdes               0.000000
name              97.698128
prefix            99.998122
neo                0.000417
pha                2.078300
H                  0.653400
diameter          85.789714
albedo            85.905100
diameter_sigma    85.803068
orbit_id           0.000000
epoch              0.000000
epoch_mjd          0.000000
epoch_cal          0.000000
equinox            0.000000
e                  0.000000
a                  0.000000
q                  0.000000
i                  0.000000
om                 0.000000
w                  0.000000
ma                 0.000104
ad                 0.000417
n                  0.000000
tp                 0.000000
tp_cal             0.000000
per                0.000417
per_y              0.000104
moid               2.078300
moid_ld            0.013250
sigma_e            2.078404
sigma_a            2.078404
sigma_q            2.078404
sigma_i            2.078404
sigma_om           2.078404
sigma_w            2.078404
sigma_ma           2.078404
sigma_ad           2.078821
sigma_n            2.078404
sigma_tp           2.078404
sigma_per          2.078821
class              0.000000
rms                0.000209
dtype: float64

In [9]:
df.id.nunique()

958524

In [10]:
df.spkid.nunique()

958524

In [11]:
df.neo.value_counts()

neo
N    935625
Y     22895
Name: count, dtype: int64

In [12]:
df.orbit_id.unique()

array(['JPL 47', 'JPL 37', 'JPL 112', ..., 'E2020H77', 'E2020K86',
       'E2020J48'], dtype=object)

In [13]:
df.equinox.value_counts()

equinox
J2000    958524
Name: count, dtype: int64

In [14]:
df['class'].unique()

array(['MBA', 'OMB', 'MCA', 'AMO', 'IMB', 'TJN', 'CEN', 'APO', 'ATE',
       'AST', 'TNO', 'IEO', 'HYA'], dtype=object)

In [15]:
#Output
df.pha.value_counts(normalize=True)

pha
N    0.997799
Y    0.002201
Name: proportion, dtype: float64

In [16]:
df_new=df.drop(columns=['id','name','pdes','prefix','equinox'],axis='columns',inplace=False)

In [17]:
df_new.shape

(958524, 40)

In [18]:
df_new = df_new.drop(columns = ['epoch_mjd', 'epoch_cal', 'ad', 'moid', 'moid_ld', 'tp_cal', 'per_y', 'sigma_ad', 'sigma_tp', 'sigma_ma','diameter','albedo','diameter_sigma','orbit_id'])

In [19]:
df_new.isnull().sum()

spkid            0
full_name        0
neo              4
pha          19921
H             6263
epoch            0
e                0
a                0
q                0
i                0
om               0
w                0
ma               1
n                0
tp               0
per              4
sigma_e      19922
sigma_a      19922
sigma_q      19922
sigma_i      19922
sigma_om     19922
sigma_w      19922
sigma_n      19922
sigma_per    19926
class            0
rms              2
dtype: int64

In [20]:
columns_to_fill=['H','sigma_e','sigma_a','sigma_q','sigma_i','sigma_om','sigma_w','sigma_n','sigma_per']

In [21]:
df_new[columns_to_fill] = df_new[columns_to_fill].fillna(df_new[columns_to_fill].mean())

In [22]:
df_new.isnull().sum()

spkid            0
full_name        0
neo              4
pha          19921
H                0
epoch            0
e                0
a                0
q                0
i                0
om               0
w                0
ma               1
n                0
tp               0
per              4
sigma_e          0
sigma_a          0
sigma_q          0
sigma_i          0
sigma_om         0
sigma_w          0
sigma_n          0
sigma_per        0
class            0
rms              2
dtype: int64

In [23]:
df_new=df_new.dropna()

In [24]:
df_new.isnull().sum()

spkid        0
full_name    0
neo          0
pha          0
H            0
epoch        0
e            0
a            0
q            0
i            0
om           0
w            0
ma           0
n            0
tp           0
per          0
sigma_e      0
sigma_a      0
sigma_q      0
sigma_i      0
sigma_om     0
sigma_w      0
sigma_n      0
sigma_per    0
class        0
rms          0
dtype: int64

In [25]:
df_new

,spkid,full_name,neo,pha,H,epoch,e,a,q,i,om,w,ma,n,tp,per,sigma_e,sigma_a,sigma_q,sigma_i,sigma_om,sigma_w,sigma_n,sigma_per,class,rms
0,2000001,1 Ceres,N,N,3.400,2458600.5,0.076009,2.769165,2.558684,10.594067,80.305531,73.597695,77.372098,0.213885,2.458239e+06,1683.145703,4.819000e-12,1.032800e-11,1.956900e-11,4.608900e-09,6.168800e-08,6.624800e-08,1.196500e-12,9.415900e-09,MBA,0.43301
1,2000002,2 Pallas,N,N,4.200,2459000.5,0.229972,2.773841,2.135935,34.832932,173.024741,310.202392,144.975675,0.213345,2.458321e+06,1687.410992,3.193400e-08,4.033700e-09,8.832200e-08,3.469400e-06,6.272400e-06,9.128200e-06,4.653600e-10,3.680700e-06,MBA,0.35936
2,2000003,3 Juno,N,N,5.330,2459000.5,0.256936,2.668285,1.982706,12.991043,169.851482,248.066193,125.435355,0.226129,2.458446e+06,1592.013769,3.052000e-08,3.471800e-09,8.139200e-08,3.223100e-06,1.664600e-05,1.772100e-05,4.413400e-10,3.107200e-06,MBA,0.33848
3,2000004,4 Vesta,N,N,3.000,2458600.5,0.088721,2.361418,2.151909,7.141771,103.810804,150.728541,95.861938,0.271609,2.458248e+06,1325.432763,2.332100e-10,1.514300e-09,1.928600e-09,2.170600e-07,3.880800e-07,1.789300e-07,2.612500e-10,1.274900e-06,MBA,0.39980
4,2000005,5 Astraea,N,N,6.900,2459000.5,0.190913,2.574037,2.082619,5.367427,141.571026,358.648418,17.846343,0.238661,2.458926e+06,1508.414421,2.373700e-08,3.970900e-09,6.092400e-08,2.740800e-06,2.894900e-05,2.984200e-05,5.522700e-10,3.490500e-06,MBA,0.52191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958519,3246801,(6013 P-L),N,N,17.135,2437203.5,0.185919,2.280861,1.856807,5.984416,194.229902,195.442802,342.057565,0.286125,2.437266e+06,1258.191614,2.142200e-02,8.779900e-01,7.299800e-01,6.969000e+00,7.433000e+00,4.631100e+01,1.652100e-01,7.264900e+02,MBA,0.23839
958520,3246834,(6331 P-L),N,N,18.500,2459000.5,0.282920,2.334910,1.674319,8.082280,355.248239,5.216223,260.113042,0.276248,2.459362e+06,1303.177916,2.642000e-07,1.885500e-08,6.256300e-07,1.563500e-05,5.598600e-05,2.380400e-04,3.346100e-09,1.578500e-05,MBA,0.53633
958521,3013075,(6344 P-L),Y,Y,20.400,2459000.5,0.662446,2.817152,0.950941,4.679278,182.982832,234.894852,240.473601,0.208444,2.459574e+06,1727.085364,6.636800e-08,9.925600e-08,1.687100e-07,1.853300e-05,5.691700e-05,8.969200e-05,1.101600e-08,9.127500e-05,APO,0.51556
958522,3246457,(2060 T-2),N,N,18.071,2441956.5,0.202053,2.373137,1.893638,0.732484,176.499082,198.026527,355.351127,0.269600,2.441974e+06,1335.311579,3.169800e-02,5.966200e-01,5.478400e-01,5.448800e-01,4.391600e+00,1.898800e+01,1.016700e-01,5.035500e+02,MBA,0.25641
958523,3246553,(2678 T-3),N,N,18.060,2443429.5,0.258348,2.260404,1.676433,9.661947,204.512448,148.496988,15.320134,0.290018,2.443377e+06,1241.302609,1.486800e-02,1.292700e-01,6.252600e-02,1.102300e+00,3.117000e-01,1.284300e+00,2.487900e-02,1.064800e+02,MBA,0.26980

In [26]:
df_new['neo'].unique()

array(['N', 'Y'], dtype=object)

In [27]:
df_new['class'].unique()

array(['MBA', 'OMB', 'MCA', 'AMO', 'IMB', 'TJN', 'CEN', 'APO', 'ATE',
       'AST', 'TNO', 'IEO'], dtype=object)

In [28]:
df_encoded = pd.get_dummies(df_new[['class']], prefix=['class'])
df_new = pd.concat([df_new, df_encoded], axis=1)

In [29]:
df_new=df_new.drop(columns='class')

In [30]:
df_new.shape

(938597, 37)

In [31]:
from sklearn.preprocessing import LabelEncoder

In [32]:
encoder=LabelEncoder()

In [33]:
columns_label=['neo','pha']

In [34]:
df_new[columns_label] = df_new[columns_label].apply(lambda col: encoder.fit_transform(col))

In [35]:
df_new

,spkid,full_name,neo,pha,H,epoch,e,a,q,i,om,w,ma,n,tp,per,sigma_e,sigma_a,sigma_q,sigma_i,sigma_om,sigma_w,sigma_n,sigma_per,rms,class_AMO,class_APO,class_AST,class_ATE,class_CEN,class_IEO,class_IMB,class_MBA,class_MCA,class_OMB,class_TJN,class_TNO
0,2000001,1 Ceres,0,0,3.400,2458600.5,0.076009,2.769165,2.558684,10.594067,80.305531,73.597695,77.372098,0.213885,2.458239e+06,1683.145703,4.819000e-12,1.032800e-11,1.956900e-11,4.608900e-09,6.168800e-08,6.624800e-08,1.196500e-12,9.415900e-09,0.43301,False,False,False,False,False,False,False,True,False,False,False,False
1,2000002,2 Pallas,0,0,4.200,2459000.5,0.229972,2.773841,2.135935,34.832932,173.024741,310.202392,144.975675,0.213345,2.458321e+06,1687.410992,3.193400e-08,4.033700e-09,8.832200e-08,3.469400e-06,6.272400e-06,9.128200e-06,4.653600e-10,3.680700e-06,0.35936,False,False,False,False,False,False,False,True,False,False,False,False
2,2000003,3 Juno,0,0,5.330,2459000.5,0.256936,2.668285,1.982706,12.991043,169.851482,248.066193,125.435355,0.226129,2.458446e+06,1592.013769,3.052000e-08,3.471800e-09,8.139200e-08,3.223100e-06,1.664600e-05,1.772100e-05,4.413400e-10,3.107200e-06,0.33848,False,False,False,False,False,False,False,True,False,False,False,False
3,2000004,4 Vesta,0,0,3.000,2458600.5,0.088721,2.361418,2.151909,7.141771,103.810804,150.728541,95.861938,0.271609,2.458248e+06,1325.432763,2.332100e-10,1.514300e-09,1.928600e-09,2.170600e-07,3.880800e-07,1.789300e-07,2.612500e-10,1.274900e-06,0.39980,False,False,False,False,False,False,False,True,False,False,False,False
4,2000005,5 Astraea,0,0,6.900,2459000.5,0.190913,2.574037,2.082619,5.367427,141.571026,358.648418,17.846343,0.238661,2.458926e+06,1508.414421,2.373700e-08,3.970900e-09,6.092400e-08,2.740800e-06,2.894900e-05,2.984200e-05,5.522700e-10,3.490500e-06,0.52191,False,False,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958519,3246801,(6013 P-L),0,0,17.135,2437203.5,0.185919,2.280861,1.856807,5.984416,194.229902,195.442802,342.057565,0.286125,2.437266e+06,1258.191614,2.142200e-02,8.779900e-01,7.299800e-01,6.969000e+00,7.433000e+00,4.631100e+01,1.652100e-01,7.264900e+02,0.23839,False,False,False,False,False,False,False,True,False,False,False,False
958520,3246834,(6331 P-L),0,0,18.500,2459000.5,0.282920,2.334910,1.674319,8.082280,355.248239,5.216223,260.113042,0.276248,2.459362e+06,1303.177916,2.642000e-07,1.885500e-08,6.256300e-07,1.563500e-05,5.598600e-05,2.380400e-04,3.346100e-09,1.578500e-05,0.53633,False,False,False,False,False,False,False,True,False,False,False,False
958521,3013075,(6344 P-L),1,1,20.400,2459000.5,0.662446,2.817152,0.950941,4.679278,182.982832,234.894852,240.473601,0.208444,2.459574e+06,1727.085364,6.636800e-08,9.925600e-08,1.687100e-07,1.853300e-05,5.691700e-05,8.969200e-05,1.101600e-08,9.127500e-05,0.51556,False,True,False,False,False,False,False,False,False,False,False,False
958522,3246457,(2060 T-2),0,0,18.071,2441956.5,0.202053,2.373137,1.893638,0.732484,176.499082,198.026527,355.351127,0.269600,2.441974e+06,1335.311579,3.169800e-02,5.966200e-01,5.478400e-01,5.448800e-01,4.391600e+00,1.898800e+01,1.016700e-01,5.035500e+02,0.25641,False,False,False,False,False,False,False,True,False,False,False,False
958523,3246553,(2678 T-3),0,0,18.060,2443429.5,0.258348,2.260404,1.676433,9.661947,204.512448,148.496988,15.320134,0.290018,2.443377e+06,1241.302609,1.486800e-02,1.292700e-01,6.252600e-02,1.102300e+00,3.117000e-01,1.284300e+00,2.487900e-02,1.064800e+02,0.26980,False,False,False,False,False,False,False,True,False,False,False,False

# Model Building

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X=df_new.drop(columns=['spkid', 'full_name', 'pha'])
y=df_new['pha']

In [38]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [39]:
df_new.pha.value_counts()/df_new.shape[0]

pha
0    0.997799
1    0.002201
Name: count, dtype: float64

# SMOTE : For balancing the dataset

In [40]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state= 42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train.ravel())

# Logistic Regression

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
LR = LogisticRegression(max_iter = 1000, penalty = 'l2', C = 1.0, solver = 'lbfgs')

In [43]:
LR.fit(X_train_res,y_train_res)

LogisticRegression(max_iter=1000)

In [44]:
from sklearn.metrics import accuracy_score,classification_report

In [45]:
y_pred=LR.predict(X_test)

In [46]:
accuracy=accuracy_score(y_test,y_pred)

In [47]:
print(accuracy)

0.8648590098728602

# Random Forest

In [48]:
from sklearn.ensemble import RandomForestClassifier

In [49]:
RF=RandomForestClassifier(n_estimators = 100, max_depth = 4, min_samples_split = 10)

In [50]:
RF.fit(X_train_res,y_train_res)

RandomForestClassifier(max_depth=4, min_samples_split=10)

In [51]:
y_pred1=RF.predict(X_test)

In [52]:
accuracy1=accuracy_score(y_test,y_pred1)

In [53]:
print(accuracy1)

0.9858619220115065